local prefix = "<localleader>"

require("neogit").setup {
  integrations = {
    -- diffview = true,
    telescope = true
  },
  use_default_keymaps = true,
  -- mappings = {
  --   commit_editor = {
  --     ["q"] = "Close",
  --     [prefix.."<c-c><c-c>"] = "Submit",
  --     [prefix.."<c-c><c-k>"] = "Abort",
  --   },
  --   rebase_editor = {
  --     [prefix.."p"] = "Pick",
  --     [prefix.."r"] = "Reword",
  --     [prefix.."e"] = "Edit",
  --     [prefix.."s"] = "Squash",
  --     [prefix.."f"] = "Fixup",
  --     [prefix.."x"] = "Execute",
  --     [prefix.."d"] = "Drop",
  --     [prefix.."b"] = "Break",
  --     ["q"] = "Close",
  --     [prefix.."<cr>"] = "OpenCommit",
  --     [prefix.."gk"] = "MoveUp",
  --     [prefix.."gj"] = "MoveDown",
  --     [prefix.."<c-c><c-c>"] = "Submit",
  --     [prefix.."<c-c><c-k>"] = "Abort",
  --   },
  --   finder = {
  --     [prefix.."<cr>"] = "Select",
  --     ["<c-c>"] = "Close",
  --     ["<esc>"] = "Close",
  --     [prefix.."<c-n>"] = "Next",
  --     [prefix.."<c-p>"] = "Previous",
  --     [prefix.."<down>"] = "Next",
  --     [prefix.."<up>"] = "Previous",
  --     [prefix.."<tab>"] = "MultiselectToggleNext",
  --     [prefix.."<s-tab>"] = "MultiselectTogglePrevious",
  --     [prefix.."<c-j>"] = "NOP",
  --   },
  --   popup = {
  --     [prefix.."?"] = "HelpPopup",
  --     [prefix.."A"] = "CherryPickPopup",
  --     [prefix.."d"] = "DiffPopup",
  --     [prefix.."M"] = "RemotePopup",
  --     [prefix.."P"] = "PushPopup",
  --     [prefix.."X"] = "ResetPopup",
  --     [prefix.."Z"] = "StashPopup",
  --     [prefix.."i"] = "IgnorePopup",
  --     [prefix.."t"] = "TagPopup",
  --     [prefix.."b"] = "BranchPopup",
  --     [prefix.."c"] = "CommitPopup",
  --     [prefix.."f"] = "FetchPopup",
  --     [prefix.."l"] = "LogPopup",
  --     [prefix.."m"] = "MergePopup",
  --     [prefix.."p"] = "PullPopup",
  --     [prefix.."r"] = "RebasePopup",
  --     [prefix.."v"] = "RevertPopup",
  --   },
  --   status = {
  --     ["q"] = "Close",
  --     [prefix.."I"] = "InitRepo",
  --     [prefix.."1"] = "Depth1",
  --     [prefix.."2"] = "Depth2",
  --     [prefix.."3"] = "Depth3",
  --     [prefix.."4"] = "Depth4",
  --     [prefix.."<tab>"] = "Toggle",
  --     [prefix.."x"] = "Discard",
  --     [prefix.."s"] = "Stage",
  --     [prefix.."S"] = "StageUnstaged",
  --     [prefix.."<c-s>"] = "StageAll",
  --     [prefix.."u"] = "Unstage",
  --     [prefix.."U"] = "UnstageStaged",
  --     [prefix.."$"] = "CommandHistory",
  --     -- [prefix.."#"] = "Console",
  --     [prefix.."Y"] = "YankSelected",
  --     [prefix.."<c-r>"] = "RefreshBuffer",
  --     [prefix.."<enter>"] = "GoToFile",
  --     [prefix.."<c-v>"] = "VSplitOpen",
  --     [prefix.."<c-x>"] = "SplitOpen",
  --     [prefix.."<c-t>"] = "TabOpen",
  --     [prefix.."{"] = "GoToPreviousHunkHeader",
  --     [prefix.."}"] = "GoToNextHunkHeader",
  --   },
  -- }
}
vim.keymap.set('n', '<leader>gg', '<cmd>Neogit<CR>', {})
