require('rmagatti.telescope')
require('rmagatti.auto-session')
require('rmagatti.session-lens')
require('rmagatti.lualine')
require('rmagatti.nvim-web-devicons')
require('rmagatti.nvim-compe')
require('rmagatti.lsp')
-- require('rmagatti.lspsaga')
require('rmagatti.treesitter')
